version: "3.8"

services:
  primary_school_frontend:
    image: portfolio_page_frontend:1.0
    container_name: portfolio_page_frontend
    build: ../
    ports: 
      - ${PORTFOLIO_PAGE_FRONTEND_PORT}:3000
    environment:
      - NEXT_PUBLIC_AUTHENTICATION_TYPE=${AUTHENTICATION_TYPE}
      - NEXT_PUBLIC_PORTFOLIO_PAGE_FRONTEND_CONTAINER_NAME=${PORTFOLIO_PAGE_FRONTEND_CONTAINER_NAME}
    networks:
      - portfolio-page
    volumes:
      - ../:/app

networks:
  portfolio-page: